### ISSUE TITLE
POST results in pre-flight OPTIONS and unnecessary function call

### ISSUE THREAD

**Issue by ebremmer** [nicolasdao/google-graphql-functions#1]
When we do POST (ie. for mutation) browser will do "pre-flight" OPTIONS call to endpoint which in my case is undesirable and doubling execution cost.This is happening because we're forced to post with "application/json".

Better would be to assume all POST's are coming as "text/plain" and body contains json string.

**Comment by nicolasdao** [comment]
Hi @ebremmer,
Sorry for the late reply. I've just added support for "text/plain" content type for POST.  

Let me know if that fixes your preflight issue.

**Comment by ebremmer** [comment]
@nicolasdao that did it, thank you!

I've also opened another suggestion to handle CORS better in #2

**Comment by nicolasdao** [comment]
Awesome @ebremmer. I'm closing this issue now. Your suggestions for CORS make perfect sense. I'll implement that asap.
