### ISSUE TITLE
CORS No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by ebremmer** [nicolasdao/google-graphql-functions#2]
It would be good to have some config option to allow handle CORS requests better. Right now with fetch you'd get

> Fetch API cannot load http://.... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://...' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by nicolasdao** [comment]
Hi @ebremmer ,

I've just released a new CORS feature. Simply update your project with the latest version, and then add a new _**webconfig.json**_ in your root project. Populate it with something like this:
```js
{
  "headers": {
    "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS, POST",
    "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Max-Age": "1296000"
  }
}
```
This new feature is details in the README.md file.

Let me know how that goes for you so I can close this ticket.

Cheers,

Nic

**Comment by nicolasdao** [comment]
Closing this issue @ebremmer . If you have a chance, let me know what you think about that fix.

**Comment by ebremmer** [comment]
@nicolasdao thanks for update.

Though I believe it would be better to dynamically control this. When you pay per function execution  you want to be sure to minimise possibly unnecessary or rouge calls.

**Comment by nicolasdao** [comment]
Makes sense @ebremmer , however, this is currently not feasible as this feature would require controlling the upstream request before it hits GCF. That might be possible by setting up Google Endpoint so GCF sits behind it. Google is currently working on a tighter integration with Google Endpoint.
