### ISSUE TITLE
DeDupe doesnt remove schema error

### ISSUE THREAD

**Issue by GxDesign** [nicolasdao/google-graphql-functions#3]
Hi, this was awesome in detail, thank you! However, when I try accessing GraphiQL, I continue to get the "Schema must be an instance of GraphQLSchema..." error and the docs dont populate with the Product type or any other info. I followed everything word for word. Any assistance please?

**Comment by nicolasdao** [comment]
Hi @GxDesign ,

Thanks for raising that issue. I'm busy now, but I should be able to have a look this weekend.

**Comment by GxDesign** [comment]
Thanks Nicolas! Looking forward to it

**Comment by nicolasdao** [comment]
Hi @GxDesign ,

I've just created an assistant called [webfunc](https://github.com/nicolasdao/webfunc) that should help you to get started with google-graphql-functions. Could you please try the following:
```
npm install webfunc -g
webfunc init graphqltest
```
Answer all the questions, and make sure you select the GraphQL project type for the first question(you will also be asked to define a Google Project and a Google Bucket, but if you don't want to set that up now, just enter anything you want. You'll be able to change that later in the webconfig.json file). 

The above will create a new project called **graphqltest** that is completely set up including google-graphql-functions and some mocked data. 

Then, run the following:
```
cd graphqltest
npm install
npm run deploy
```

If that works, then simply open the different files in that project. It is super lean, so you should be able to make sense of all of this. 

I'm planning to add more feature and templates in [webfunc](https://github.com/nicolasdao/webfunc), so please feel free to have a look and give me your feedback if you have a chance. If you like it, don't hesitate to give me a star ;).

Let me know how that goes.
